# Generated by Django 3.0.7 on 2020-06-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=250)),
                ('instrument', models.CharField(max_length=200)),
                ('dateOfBirth', models.DateField(auto_now=True, null=True)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'default_related_name': 'singer',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('singer', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('created_datetime', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'default_related_name': 'song',
            },
        ),
    ]
