# Generated by Django 3.0.7 on 2020-06-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicLife', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='avatar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='singer',
            name='avatar2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
